server:
  port: 9191

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: #username
    password: #password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}