server:
  port: 9191

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: #username
    password: #password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  messages:
    basename: i18n/messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: #Replace this field with your Gmail username.
    password: #Replace this field with your Gmail password.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  thymeleaf:
    mode: HTML
    cache: true

logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}