server:
  port: 9000

spring:
  application:
    name: baby-service
  datasource:
    url: jdbc:postgresql://localhost/baby
    username: portal #username
    password: portal #password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/master.xml

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
    resource:
      user-info-uri: http://localhost:8100/auth/oauth/account/me

logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
